<% require 'dotenv/load' %>:concurrency: <%= ENV.fetch("SIDEKIQ_PROMPT_REPORTS_CONCURRENCY") { 3 } %>
:timeout: 600
:pidfile: ./tmp/pids/sidekiq_prompt_reports_<%= ENV.fetch("WORKER_INDEX") { "NOINDEX" } %>.pid
:logfile: ./log/sidekiq_prompt_reports.log
:tag:
  - sidekiq_prompt_reports
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
  - <%= 'WORKER_' + ENV.fetch("WORKER_INDEX") { "NOINDEX" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - CreateTestReportWorker
  - ForceCreatePromptReportWorker
  - CreatePeriodicReportWorker
  - CreatePromptReportWorker
  - StartSendingPeriodicReportsWorker
  - StartSendingPromptReportsWorker
